'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('Menus', [{
      name: '김치찌개',
      spicy: true,
      meat: true,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '된장찌개',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '순두부찌개',
      spicy: true,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '뼈다귀 해장국',
      spicy: true,
      meat: true,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '동태찌개',
      spicy: true,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '버섯 전골',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '청국장',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '비지찌개',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '고추장찌개',
      spicy: true,
      meat: true,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '부대찌개',
      spicy: true,
      meat: true,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '아구탕',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '해물탕',
      spicy: true,
      meat: true,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '내장탕',
      spicy: true,
      meat: true,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '알탕',
      spicy: true,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '꽃게탕',
      spicy: true,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '매운탕',
      spicy: true,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '연포탕',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '추어탕',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '아구찜',
      spicy: true,
      meat: false,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '장어구이',
      spicy: false,
      meat: false,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '간장게장',
      spicy: false,
      meat: false,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '양념게장',
      spicy: true,
      meat: false,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '물회',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '낙지볶음',
      spicy: true,
      meat: false,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '제육볶음',
      spicy: true,
      meat: true,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '순대볶음',
      spicy: true,
      meat: true,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '오징어볶음',
      spicy: true,
      meat: false,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '회덮밥',
      spicy: false,
      meat: false,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '잔치국수',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'noodle'
    }, {
      name: '라면',
      spicy: true,
      meat: false,
      soup: true,
      style: 'others',
      type: 'noodle'
    }, {
      name: '막국수',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'noodle'
    }, {
      name: '냉면',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'noodle'
    }, {
      name: '칼국수',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'noodle'
    }, {
      name: '쫄면',
      spicy: false,
      meat: false,
      soup: true,
      style: 'others',
      type: 'noodle'
    }, {
      name: '쌀국수',
      spicy: false,
      meat: false,
      soup: true,
      style: 'asian',
      type: 'noodle'
    }, {
      name: '콩국수',
      spicy: false,
      meat: false,
      soup: true,
      style: 'korean',
      type: 'noodle'
    }, {
      name: '우동',
      spicy: false,
      meat: false,
      soup: true,
      style: 'others',
      type: 'noodle'
    }, {
      name: '찜닭',
      spicy: true,
      meat: true,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '닭갈비',
      spicy: true,
      meat: true,
      soup: false,
      style: 'korean',
      type: 'rice'
    }, {
      name: '닭볶음탕',
      spicy: true,
      meat: true,
      soup: true,
      style: 'korean',
      type: 'rice'
    }, {
      name: '치킨',
      spicy: false,
      meat: true,
      soup: false,
      style: 'korean',
      type: 'others'
    }, {



      
      name: '초밥',
      spicy: false,
      meat: false,
      soup: false,
      style: 'japanese',
      type: 'rice'
    }, {
      name: '짜장면',
      spicy: false,
      meat: false,
      soup: false,
      style: 'chinese',
      type: 'noodle'
    }, {
      name: '짬뽕',
      spicy: true,
      meat: false,
      soup: true,
      style: 'chinese',
      type: 'noodle'
    }])
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('Menus', null, {});
  }
};
